import { Product, SpecialOffer } from '../types';

export const PRODUCTS: Product[] = [
  {
    id: 'soup',
    name: 'Tomato Soup',
    price: 0.65,
    unit: 'tin',
    emoji: '🥣',
    category: 'Pantry',
    description: 'Rich, vine-ripened tomato bisque',
    origin: 'Devon, UK',
    badge: 'Offer',
  },
  {
    id: 'bread',
    name: 'Sourdough',
    price: 0.80,
    unit: 'loaf',
    emoji: '🍞',
    category: 'Bakery',
    description: 'Slow-fermented artisan loaf',
    origin: 'Local Bakery',
    badge: 'Offer',
  },
  {
    id: 'milk',
    name: 'Whole Milk',
    price: 1.30,
    unit: 'bottle',
    emoji: '🥛',
    category: 'Dairy',
    description: 'Full-fat organic whole milk',
    origin: 'Yorkshire',
    badge: 'Offer',
  },
  {
    id: 'apples',
    name: 'Pink Lady Apples',
    price: 1.00,
    unit: 'bag',
    emoji: '🍎',
    category: 'Produce',
    description: 'Crisp, sweet Australian variety',
    origin: 'Kent, UK',
    badge: '10% Off',
  },
  {
    id: 'eggs',
    name: 'Free Range Eggs',
    price: 2.40,
    unit: 'dozen',
    emoji: '🥚',
    category: 'Dairy',
    description: 'Golden-yolk free range eggs',
    origin: 'Norfolk Farms',
    badge: 'Offer',
  },
  {
    id: 'butter',
    name: 'Salted Butter',
    price: 1.75,
    unit: 'block',
    emoji: '🧈',
    category: 'Dairy',
    description: 'Slow-churned cultured butter',
    origin: 'Normandy, FR',
    badge: 'New',
  },
  {
    id: 'pasta',
    name: 'Rigatoni',
    price: 1.20,
    unit: 'pack',
    emoji: '🍝',
    category: 'Pantry',
    description: 'Bronze-die cut durum wheat',
    origin: 'Abruzzo, IT',
  },
  {
    id: 'coffee',
    name: 'Filter Coffee',
    price: 3.50,
    unit: 'bag',
    emoji: '☕',
    category: 'Drinks',
    description: 'Single origin, medium roast',
    origin: 'Ethiopia',
    badge: 'Popular',
  },
  {
    id: 'orange-juice',
    name: 'Orange Juice',
    price: 1.89,
    unit: 'carton',
    emoji: '🍊',
    category: 'Drinks',
    description: 'Freshly squeezed, no added sugar',
    origin: 'Valencia, ES',
  },
  {
    id: 'cheese',
    name: 'Mature Cheddar',
    price: 2.80,
    unit: 'block',
    emoji: '🧀',
    category: 'Dairy',
    description: '18-month aged farmhouse cheddar',
    origin: 'Somerset, UK',
    badge: 'Aged',
  },
  {
    id: 'tomatoes',
    name: 'Cherry Tomatoes',
    price: 1.10,
    unit: 'punnet',
    emoji: '🍅',
    category: 'Produce',
    description: 'Vine-grown on the vine',
    origin: 'Spain',
  },
  {
    id: 'chicken',
    name: 'Chicken Breast',
    price: 3.99,
    unit: 'pack',
    emoji: '🍗',
    category: 'Meat',
    description: 'Free-range, skinless fillets',
    origin: 'British Farm',
    badge: 'Fresh',
  },
  {
    id: 'salmon',
    name: 'Atlantic Salmon',
    price: 4.50,
    unit: 'fillet',
    emoji: '🐟',
    category: 'Fish',
    description: 'Sustainably sourced fillet',
    origin: 'Scottish Waters',
    badge: 'MSC',
  },
  {
    id: 'yogurt',
    name: 'Greek Yogurt',
    price: 1.60,
    unit: 'pot',
    emoji: '🫙',
    category: 'Dairy',
    description: 'Thick, strained full-fat yogurt',
    origin: 'Greece',
  },
  {
    id: 'spinach',
    name: 'Baby Spinach',
    price: 1.30,
    unit: 'bag',
    emoji: '🥬',
    category: 'Produce',
    description: 'Tender young leaves, triple-washed',
    origin: 'Lincolnshire, UK',
  },
  {
    id: 'honey',
    name: 'Wild Flower Honey',
    price: 3.20,
    unit: 'jar',
    emoji: '🍯',
    category: 'Pantry',
    description: 'Raw, unfiltered wildflower honey',
    origin: 'Wales, UK',
    badge: 'Raw',
  },
];

export const SPECIAL_OFFERS: SpecialOffer[] = [
  {
    id: 'offer-apples',
    productId: 'apples',
    description: '10% off Pink Lady Apples',
    type: 'PERCENTAGE_OFF',
    percentOff: 10,
  },
  {
    id: 'offer-soup-bread',
    productId: 'bread',
    description: 'Buy 2 tins of soup, get a loaf of bread half price',
    type: 'BUY_N_GET_M_FREE',
    buyQuantity: 2,
    freeQuantity: 1,
  },
  {
    id: 'offer-milk',
    productId: 'milk',
    description: 'Buy 3 bottles of milk for the price of 2',
    type: 'BUY_N_GET_M_FREE',
    buyQuantity: 3,
    freeQuantity: 1,
  },
  {
    id: 'offer-eggs',
    productId: 'eggs',
    description: 'Buy 2 dozen eggs, get £0.80 off',
    type: 'MULTIBUY',
    multiQuantity: 2,
    multiPrice: 4.00,
  },
  {
    id: 'offer-coffee',
    productId: 'coffee',
    description: 'Buy 2 bags of coffee, save £1.00',
    type: 'MULTIBUY',
    multiQuantity: 2,
    multiPrice: 6.00,
  },
];

export const CURRENCY_SYMBOL = '£';

export const CATEGORIES = [
  'All',
  'Produce',
  'Dairy',
  'Bakery',
  'Pantry',
  'Drinks',
  'Meat',
  'Fish',
];